
4.1 Warming Up Exercise: Basic Vector and Matrix Operation with Numpy.
Problem - 1: Array Creation:
Complete the following Tasks:
1. Initialize an empty array with size 2X2.
2. Initialize an all one array with size 4X2.
3. Return a new array of given shape and type, filled with fill value.{Hint: np.full}
4. Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}
5. Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}
6. For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np
#Create an empty array of 2X2 size using np.empty
empty_array=np.empty((2,2))
#Print the array
print("Empty array of 2x2 size: \n",empty_array)

Empty array of 2x2 size: 
 [[5.0227160e-310 0.0000000e+000]
 [6.7999229e-310 6.7999229e-310]]


In [ ]:
import numpy as np
#Create a 4X2 array with all elements as 1 using np.ones
one_array=np.ones((4,2))
#Print the array
print("All one array of size 4x2:\n",one_array)

All one array of size 4x2:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
import numpy as np
#Create a 2x3 array with all elements as 3
new_array=np.full((2,3),3,dtype=int) #dtype shows that the array should have integer data type
#print the array
print("New array of given shape and type:\n",new_array)

New array of given shape and type:
 [[3 3 3]
 [3 3 3]]


In [ ]:
import numpy as np
#Create a 2x3 array using np.array
array=np.array([[1,2,3],[4,5,6]])
#Create a new array with same shape as array but filled with zeros
new_array=np.zeros_like(array)
#Print the new array
print("New array: \n",new_array)

New array: 
 [[0 0 0]
 [0 0 0]]


In [ ]:
import numpy as np
#Create 2x3 array using np.array
array=np.array([[1,2,3],[4,5,6]])
#Create a new array with same shape as array but filled with ones
new_array=np.ones_like(array)
#Print the new array
print("New array: \n",new_array)

New array: 
 [[1 1 1]
 [1 1 1]]


In [ ]:
import numpy as np
#Create a simple python list
new_list=[1,2,3,4]
#Convert python list to numpy array using np.array
numpy_array=np.array(new_list)
#print the array
print("Converted array:\n",numpy_array)

Converted array:
 [1 2 3 4]


4.1.1 Problem - 2: Array Manipulation: Numerical Ranges and Array indexing:
Complete the following tasks:
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.
2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}
3. Create a 3X3 identity matrix.{Hint:np.eye()}
4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}
5. Create a 10X10 array with random values and find the minimum and maximum values.
6. Create a zero array of size 10 and replace 5th element with 1.
7. Reverse an array arr = [1,2,0,0,4,0].
8. Create a 2d array with 1 on border and 0 inside.
9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np
a=np.arange(10,49)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [ ]:
import numpy as np
a=np.arange(9)
matrix=a.reshape(3,3)
print("3x3 matrix:\n",matrix)

3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
import numpy as np
matrix=np.eye(3)
print("3x3 Identity Matrix:\n",matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
import numpy as np
array=np.random.random(30);
mean_array=array.mean();
print(mean_array);

0.4908887687574654


In [ ]:
import numpy as np
array=np.random.random((10,10));
min_value=array.min();
max_value=array.max();
print("Minimum Value: ",min_value,"\nMaximum Value: ",max_value);

Minimum Value:  0.01901098865349138 
Maximum Value:  0.9955442964440274


In [ ]:
import numpy as np
zero_array=np.zeros(10);
zero_array[4]=1;
print(zero_array);

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [ ]:
import numpy as np
arr=[1,2,0,0,4,0];
reversed_array=arr[::-1];
print(reversed_array)

[0, 4, 0, 0, 2, 1]


In [ ]:
import numpy as np
array=np.ones((5,5));
array[1:-1,1:-1]=0;
print(array)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
import numpy as np
arr=np.zeros((8,8));
arr[1::2,::2]=1;
arr[::2,1::2]=1;
print(arr)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Problem - 3: Array Operations:
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.
2. Subtract the two array.
3. Multiply the array with any integers of your choice.
4. Find the square of each element of the array.
5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.
6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.
7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#adding two array
add1=np.add(x,y);
add2=np.add(v,w);
print("Addition of x and y:\n",add1)
print("Addition of v and w: ",add2)

Addition of x and y:
 [[ 6  8]
 [10 13]]
Addition of v and w:  [20 22]
Diffference of x and y:
 [[-4 -4]
 [-4 -3]]
Difference of v and w:  [-2 -2]
Multiplication of x and y with integer:
 [[[ 2  4]
  [ 6 10]]

 [[10 12]
  [14 16]]]
Multiplication of v and w with integer:  [[27 30]
 [33 36]]
Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#Subtracting two array
sub1=np.subtract(x,y);
sub2=np.subtract(v,w);
print("Diffference of x and y:\n",sub1)
print("Difference of v and w: ",sub2)

Diffference of x and y:
 [[-4 -4]
 [-4 -3]]
Difference of v and w:  [-2 -2]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#Multiplying array with a random integer
mul1=np.multiply((x,y),2);
mul2=np.multiply((v,w),3);
print("Multiplication of x and y with integer:\n",mul1)
print("Multiplication of v and w with integer:\n",mul2)

Multiplication of x and y with integer:
 [[[ 2  4]
  [ 6 10]]

 [[10 12]
  [14 16]]]
Multiplication of v and w with integer:
 [[27 30]
 [33 36]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#finding square of each element of array
sq1=np.square(x);
sq2=np.square(y);
sq3=np.square(v);
sq4=np.square(w);
print("Square of x:\n",sq1);
print("Square of y:\n",sq2);
print("Square of v:\n",sq3);
print("Square of w:\n",sq4);

Square of x:
 [[ 1  4]
 [ 9 25]]
Square of y:
 [[25 36]
 [49 64]]
Square of v:
 [ 81 100]
Square of w:
 [121 144]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#finding dot product between v and w
dp1=np.dot(v,w);
print("Dot product of v and w: ",dp1)
#finding dot product of x and v
dp2=np.dot(x,v);
print("Dot product of x and v:\n",dp2)
#finding dot product of x and y
dp3=np.dot(x,y);
print("Dot product of x and y:\n",dp3)

Dot product of v and w:  219
Dot product of x and v:
 [29 77]
Dot product of x and y:
 [[19 22]
 [50 58]]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#Concatenating x and y along the x-axis
concat1=np.concatenate((x,y),axis=1);
print("Concatenation of x and y along the x-axis:\n",concat1);
#Concatenating v and w along the y-axis
concat2=np.concatenate((v,w),axis=0);
print("Concatenation of v and w along the y-axis:\n",concat2);

Concatenation of x and y along the x-axis:
 [[1 2 5 6]
 [3 5 7 8]]
Concatenation of v and w along the y-axis:
 [ 9 10 11 12]


In [ ]:
import numpy as np
x=np.array([[1,2],[3,5]]);
y=np.array([[5,6],[7,8]]);
v=np.array([9,10]);
w=np.array([11,12]);
#Concatenating x and v
concat=np.concatenate(x,v);
print(concat)

TypeError: only integer scalar arrays can be converted to a scalar index

TypeError is observed because the dimension of both array should be same while concatenating but here x is 2D and v is 1D.

Problem - 4: Matrix Operations:
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.
2. Prove AB ̸= BA.
3. Prove (AB)T = BTAT
.

• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}
• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]]);
B = np.array([[5,3],[2,1]]);
#Calculate inverse of matrix A using linalg function
A_inverse=np.linalg.inv(A)
#Multiply matrix A to its inverse to verify the equation
I=np.dot(A,A_inverse)
#print the result that should be identity matrix
print("A*A^(-1):\n",I)

A*A^(-1):
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]]);
B = np.array([[5,3],[2,1]]);
#Multiply matrices using np.dot
AB=np.dot(A,B);
BA=np.dot(B,A)
#Print the results
print("AB:\n",AB)
print("BA:\n",BA)

AB:
 [[23 13]
 [51 29]]
BA:
 [[36 44]
 [13 16]]


In [ ]:
import numpy as np
A = np.array([[3,4],[7,8]]);
B = np.array([[5,3],[2,1]]);
#Multiply two matrices using np.dot
AB=np.dot(A,B)
#find transpose of matrices using np.transpose
ABT=np.transpose(AB)
AT=np.transpose(A)
BT=np.transpose(B)
BTAT=np.dot(BT,AT)
#Print the results to prove the equation
print("(AB)^T:\n",ABT)
print("(B)^T(A)^T: \n",BTAT)

(AB)^T:
 [[23 51]
 [13 29]]
(B)^T(A)^T: 
 [[23 51]
 [13 29]]


In [ ]:
import numpy as np
A = np.array([[2,-3,1],[1,-1,2],[3,1,-1]]);
B = np.array([-1,-3,9]);
#Calculate the inverse of matrix A using np.linalg.inv()
A_inverse=np.linalg.inv(A)
#Multiply inverse of A to matrix B using np.dot
X=np.dot(A_inverse,B)
#print the solution
print("So the values of x,y and z are:",X)

So the values of x,y and z are: [ 2.  1. -2.]


Linear algebra(linalg) function makes it easier to perform operations commonly used in mathematics and Machine Learning.This can be used for matrix inversion(np.linalg.inv(A)), finding determinant(np.linalg.det(A)) and solving linear systems(np.linalg.solve(A,B)).

4.2 Experiment: How Fast is Numpy?
In this exercise, you will compare the performance and implementation of operations using plain Python
lists (arrays) and NumPy arrays. Follow the instructions:
1. Element-wise Addition:
• Using Python Lists, perform element-wise addition of two lists of size 1, 000, 000. Measure
and Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
from timeit import timeit
#Define addition functions
def add_python(Z1,Z2):
  return[z1+z2 for z1,z2 in zip(Z1,Z2)]
def add_numpy(Z1,Z2):
  return np.add(Z1,Z2)
#Generate random sample data
size=1000000
Z1_list=[i for i in range(size)]
Z2_list=[i for i in range(size)]
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
#Time the execution of each function
python_time=timeit("add_python(Z1_list,Z2_list)",globals=globals(),number=100)
numpy_time=timeit("add_numpy(Z1_np,Z2_np)",globals=globals(),number=100)
#Print results
print(f"Pure Python addition:{python_time:.6f}seconds per loop")
print(f"NumPy addition:{numpy_time:.6f}seconds per loop")

Pure Python addition:9.292708seconds per loop
NumPy addition:0.127785seconds per loop


2. Element-wise Multiplication

• Using Python Lists, perform element-wise multiplication of two lists of size 1, 000, 000. Mea-
sure and Print the time taken for this operation.

• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
from timeit import timeit
#Define multiplication functions
def mul_python(Z1,Z2):
  return[z1*z2 for z1,z2 in zip(Z1,Z2)]
def mul_numpy(Z1,Z2):
  return np.multiply(Z1,Z2)
#Generate random sample data
size=1000000
Z1_list=[i for i in range(size)]
Z2_list=[i for i in range(size)]
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
#Time the execution of each function
python_time=timeit("mul_python(Z1_list,Z2_list)",globals=globals(),number=100)
numpy_time=timeit("mul_numpy(Z1_np,Z2_np)",globals=globals(),number=100)
#Print results
print(f"Pure Python multiplication:{python_time:.6f}seconds per loop")
print(f"NumPy multiplication:{numpy_time:.6f}seconds per loop")

Pure Python multiplication:10.586792seconds per loop
NumPy multiplication:0.147762seconds per loop


3. Dot Product
• Using Python Lists, compute the dot product of two lists of size 1, 000, 000. Measure and
Print the time taken for this operation.
• Using Numpy Arrays, Repeat the calculation and measure and print the time taken for this
operation.

In [ ]:
import numpy as np
import random
from timeit import timeit
#Define dot product functions
def dot_python(Z1,Z2):
  return sum(z1*z2 for z1,z2 in zip(Z1,Z2))
def dot_numpy(Z1,Z2):
  return np.dot(Z1,Z2)
#Generate random sample data
size=1000000
Z1_list=random.sample(range(size+1),size)
Z2_list=random.sample(range(size+1),size)
Z1_np=np.array(Z1_list)
Z2_np=np.array(Z2_list)
#Time the execution of each function
python_time=timeit("dot_python(Z1_list,Z2_list)",globals=globals(),number=100)
numpy_time=timeit("dot_numpy(Z1_np,Z2_np)",globals=globals(),number=100)
#Print results
print(f"Pure Python dot product:{python_time:.6f}seconds per loop")
print(f"NumPy dot product:{numpy_time:.6f}seconds per loop")

Pure Python dot product:36.073293seconds per loop
NumPy dot product:0.146366seconds per loop


4. Matrix Multiplication
• Using Python lists, perform matrix multiplication of two matrices of size 1000x1000. Measure
and print the time taken for this operation.

• Using NumPy arrays, perform matrix multiplication of two matrices of size 1000x1000. Mea-
sure and print the time taken for this operation.

In [ ]:
import numpy as np
import random
from timeit import timeit
#Define matrix multiplication functions
def matrix_mul_python(A,B):
  size=len(A)
  result=[[0]*size for _ in range(size)]
  for i in range(size):
    for j in range(size):
      for k in range(size):
        result[i][j]+=A[i][k]*B[k][j]
  return result
def matrix_mul_numpy(A,B):
  return np.dot(A,B)
#Generate two 1000X1000 sized matrices with random integers from 0 to 10
size=1000
A_list=[[random.randint(0,10)for _ in range(size)] for _ in range(size)]
B_list=[[random.randint(0,10)for _ in range(size)] for _ in range(size)]
A_np=np.random.randint(0,11,size=(size,size))
B_np=np.random.randint(0,11,size=(size,size))
#Time the execution of each funcion
python_time=timeit("matrix_mul_python(A_list,B_list)",globals=globals(),number=1)
numpy_time=timeit("matrix_mul_numpy(A_np,B_np)",globals=globals(),number=1)
#Print results
print(f"Pure Python matrix multiplication :{python_time:.6f}seconds per loop")
print(f"NumPy matrix multiplication:{numpy_time:.6f}seconds per loop")

Pure Python matrix multiplication :240.329084seconds per loop
NumPy matrix multiplication:2.063000seconds per loop
